### ISSUE TITLE
libshumate package deleted from aur

### ISSUE THREAD

**Issue by spsf64** [ogarcia/pkgbuilds#11]
What happened? Did you request the deletion?
Hope you resubmit it!

**Comment by ogarcia** [comment]
No, it has been moved to the official repository. What happens is that it has entered the [testing repository](https://archlinux.org/packages/testing/x86_64/libshumate/), that's why you see it neither with pacman nor with the AUR helper.

Most likely in a few days it will be moved to a stable repository in conjunction with all GNOME 43.

**Comment by spsf64** [comment]
Ahhh ok, good to known!
Thanks for the prompt reply
